### ISSUE TITLE
FR: multpile input devices

### ISSUE THREAD

**Issue by subutux** [wackerl91/luna#54] opened 2016-03-10 08:34 UTC
Hi all! May i say that your work is just awesome?! I love the fact that's so well reconcilable with Kodi, especially with the OSMC theme!

I would be handy if we are able to set multiple input devices in settings (for ex. two xbox360 controllers, keyboard and mouse..) because from my understanding, this is currently not possible. Or am I wrong?

**Comment by wackerl91** [comment] 2016-03-15 18:01
That's currently not possible, you're completely right. Multiple controllers of the same type should definitely be supported by moonlight-embedded. However, mix and match (one X360 + Mouse / Keyboard) most likely isn't.
I suspect something like split screen coop is your aim here?
Either way, I'll have a look into this as a feature for the next release (might take a while, don't have much time at the moment).

**Comment by wackerl91** [comment] 2016-04-02 00:26
@subutux Getting along pretty well with this, at least as far as multiple controllers (of the same type) are concerned. Since this feature has been a lot of work already I'll most likely split it into two features. While you can expect to set up two four controllers when 0.6.0 is released, dedicated keyboard and mouse support won't make it until then - this is partly due to how moonlight-embedded works, as it accepts only a single map file for all the input devices listed. If there's no input device specified it (theoretically, never tested this) reads from all devices but doesn't accept a controller map. Most of the commands which are 'buried' deep inside Luna won't work with this kind of flexibility so the kb/m support will come at a later date (if enough people are interested).

Here's a screenshot of the new input selection (yeah, pretty empty, I know ...):
![screenshot009](https://cloud.githubusercontent.com/assets/9624014/14222957/26302784-f878-11e5-9d86-6f0eae2ebf34.png)

**Comment by subutux** [comment] 2016-04-02 09:35
Wow sounds good! I was under the assumption that you could define multiple input devices with their own mapping after each other . Like so:
'''
--mapping <file for input1> --input <input1> --mapping <file for input2> --input input2 
'''

When I want to play a game, I usually steam steam first and go from there, with keyboard and mouse & while launching a game, I switch over to a controller.

Nevertheless, multiple controllers sounds awesome! Looking forward to it!

**Comment by wackerl91** [comment] 2016-04-02 12:57
@subutux I might have misunderstood moonlight's documentation there, sorry :disappointed: Thanks for correcting me!
I'll give this a shot (based on your use case above) and if it works I'll make sure Luna properly supports this.

**Comment by wackerl91** [comment] 2016-04-09 10:55
@subutux: The changes have just been merged back to the develop branch. If you want to you can give this a try before 0.6.0. is released by uninstalling your currently installed version and reinstall from develop - just be aware that the ZIP provided by GitHub might not pass Kodi's structure validation, so you might need to unzip it, rename the folder from 'luna-develop' to 'script.luna-develop' und zip it again.

**Closed by wackerl91** 2016-04-09 10:55 UTC
Labels: feature request

**Comment by subutux** [comment] 2016-04-09 11:04
Thanks! I'll test this when I've got the time (probably tomorrow).

**Comment by wackerl91** [comment] 2016-04-09 11:09
Take your time. If you run into any problems I'd really appreciate it if you open separate issues!

**Comment by subutux** [comment] 2016-04-09 11:11
We'll do!

**Comment by cricket007** [comment] 2016-06-21 17:47
@wackerl91, 
Hi, I stumbled upon this feature with the latest update and I understand this addon is primarily focused on OSMC, but I use the Confluence theme, and while the new input selection window is functional, it doesn't "flow" well with the rest of the UI. The rest of the dialogs seem to be properly implemented in the Confluence theme, so I was wondering if that was a bug?

**Comment by wackerl91** [comment] 2016-06-21 18:03
Heya @cricket007,
it's not a bug, it's a feature :P
Seriously though, most of the windows (like the main screen, games list, ...) didn't have views attached and thus used the default file listing view of the selected skin (same goes for the context menu). The input selection however had to be coded in Python due to its complexity and has fixed assets currently.
That being said: I'm currently in the process of transitioning to XML Windows so,
a) Luna will look the same on any skin, for all views
b) this potentially gives skinners or users the opportunity to override Luna's XMLs and provide ones matching their skin.

Let me know if you have any further questions, I'm happy to answer :)

**Comment by steven6282** [comment] 2016-06-22 04:16
Hey, sorry if this isn't the correct place to post this, but I'm having issues getting a XBox 360 controller working under Luna 0.6.2.  I've got a fresh raspberry pi 2 setup with OSMC, installed moonlight, xboxdrv got it set to autostart, etc.  The controller connects fine, if I manually launch xboxdrv without --silent I see the input being detected.  However, it's not working when streaming starts.  I've tried manually adding it as a controller with a map file, tried creating a map file as well and it doesn't appear to detect anything while creating the map file either.

I had this working fine on a pi 1 with Luna 0.5.3 so not sure what I'm doing wrong here, all the same steps were taken.

Is there any known problems atm, or something I might be missing, or is there more information I can provide to figure out what the problem might be?

**Comment by wackerl91** [comment] 2016-06-22 22:13
Heya @steven6282,
> sorry if this isn't the correct place to post this

This totally isn't the right place, as this issue is about a feature request that's already implemented (and questions regarding it, like @cricket007's).

I don't mean to be nasty about this in any way, but I like to keep the issues somewhat organised. That being said, I'd kindly ask you to open a new issue and paste your text in there so we can have a meaningful discussion about the problem you're seeing. I'm always happy to help and resolve any bugs on my end as quickly as possible and I really do appreciate your input - I'd just like to give other people (experiencing the same issue) the opportunity to easily find the related discussion on the issue tracker. Plus, having a new GitHub issue regarding a new problem makes it way easier for me to track what has to be done maintenance wise and prioritise accordingly.

Thanks for your understanding.
