### ISSUE TITLE
Pairing Issues

### ISSUE THREAD

**Issue by AaronMesa** [wackerl91/luna#28] opened 2016-01-17 18:52 UTC
Every time I try pairing it throws this error
10:48:21 1318.747681 T:1576006688  NOTICE: -->Python Interpreter Initialized<--
10:48:23 1320.040649 T:1576006688  NOTICE: Bootstrapper called
10:48:23 1320.369873 T:1576006688  NOTICE: Core Init
10:48:23 1320.370850 T:1576006688  NOTICE: [script.luna] Update Service init
10:48:24 1320.966064 T:1576006688  NOTICE: [xbmcswift2] Request for "/actions/pair-host" matches rule for function "pair_host"
10:48:24 1320.966431 T:1576006688  NOTICE: Core Init
10:48:24 1320.990601 T:1576006688   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not iterable
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/luna-master/addon.py", line 135, in <module>
                                                plugin.run()
                                              File "/home/osmc/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 332, in run
                                                items = self._dispatch(self.request.path)
                                              File "/home/osmc/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 306, in _dispatch
                                                listitems = view_func(**items)
                                              File "/home/osmc/.kodi/addons/luna-master/addon.py", line 66, in pair_host
                                                config_controller.pair_host()
                                              File "/home/osmc/.kodi/addons/luna-master/resources/lib/controller/configcontroller.py", line 60, in pair_host
                                                success = self.moonlight_helper.pair_host(pair_dialog)
                                              File "/home/osmc/.kodi/addons/luna-master/resources/lib/util/moonlighthelper.py", line 67, in pair_host
                                                pairing_proc = subprocess.Popen([self.config_helper.get_binary(), 'pair', self.plugin.get_setting('host')],
                                              File "/home/osmc/.kodi/addons/luna-master/resources/lib/util/confighelper.py", line 158, in get_binary
                                                cp.read(self.full_path)
                                              File "/usr/lib/python2.7/ConfigParser.py", line 300, in read
                                                for filename in filenames:
                                            TypeError: 'NoneType' object is not iterable
                                            -->End of Python script error report<--
10:48:24 1321.112793 T:1576006688 WARNING: CPythonInvoker(22, /home/osmc/.kodi/addons/luna-master/addon.py): the python script "/home/osmc/.kodi/addons/luna-master/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE

**Comment by wackerl91** [comment] 2016-01-18 15:52
Heya @AaronMesa,
this looks like an attempt to read the config file before it was actually created.
Just so I can try and reproduce this: did you call the settings via the context menu (without actually launching the addon) or from inside Luna?

**Comment by Haapavuo** [comment] 2016-01-29 19:01
Same problem here. No matter how I try to pair the devices.

**Comment by wackerl91** [comment] 2016-01-29 19:52
Hey!
@Haapavuo thanks for the input. I'll try to have a look at this tomorrow.
It might be possible that the config file isn't created properly for some reason.

**Comment by wackerl91** [comment] 2016-01-30 14:36
This should be resolved in [Luna 0.4.1-alpha](https://github.com/wackerl91/luna/releases/tag/v0.4.1-alpha).
If you can launch the add-on you should be able to update using the 'Check for Updates' menu item. Otherwise please uninstall and reinstall the new version.

**Closed by wackerl91** 2016-01-30 14:36 UTC
Labels: bug
